# Generated by Django 4.2.2 on 2023-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xorchiper', '0002_alter_enkripsifiles_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enkripsifiles',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
