# Generated by Django 4.2.2 on 2023-06-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xorchiper', '0006_enkripsifiles_encrypted_by_enkripsifiles_fi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enkripsifiles',
            name='fi',
            field=models.FileField(blank=True, upload_to='encryptedFiles'),
        ),
    ]
