# Generated by Django 4.2.2 on 2023-06-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xorchiper', '0009_enkripsifiles_fi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enkripsifiles',
            name='fi',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
