# Generated by Django 4.2.2 on 2023-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xorchiper', '0011_dekripsifiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkripsifiles',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
