# Generated by Django 4.2.2 on 2023-06-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xorchiper', '0012_enkripsifiles_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dekripsifiles',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
